### Question 1: Represent matrix, vector and scalar in Python
Hint: You may use numpy library, shape(), type(), dtype.

In [8]:
import numpy as np

# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
x           = np.array([[1., 2., 3.],[4., 5., 6.]])
size_x      = x.shape
type_x      = x.dtype

y           = np.array([1., 2., 3.])
size_y      = y.shape
type_y      = y.dtype

z           = np.array([1.])
size_z      = z.shape
type_z      = z.dtype
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('x = ')
print(x)
print('******************************')
print('size of x = ')
print(size_x)
print('******************************')
print('type of x = ')
print(type_x)

print('******************************')
print('y = ')
print(y)
print('******************************')
print('size of y = ')
print(size_y)
print('******************************')
print('type of y = ')
print(type_y)

print('******************************')
print('z = ')
print(z)
print('******************************')
print('size of z = ')
print(size_z)
print('******************************')
print('type of z = ')
print(type_z)
print('******************************')

******************************
x = 
[[1. 2. 3.]
 [4. 5. 6.]]
******************************
size of x = 
(2, 3)
******************************
type of x = 
float64
******************************
y = 
[1. 2. 3.]
******************************
size of y = 
(3,)
******************************
type of y = 
float64
******************************
z = 
[1.]
******************************
size of z = 
(1,)
******************************
type of z = 
float64
******************************
