### Question 4: Multiply the two matrices in Python

In [17]:
import numpy as np

# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
A       = np.array([[1., 2.],
                    [3., 4.],
                    [5., 6.]])
size_A  = A.shape

X       = np.array([[10., 20.],
                    [30., 40.]])
size_X  = X.shape

Y       = np.matmul(A,X)
size_Y  = Y.shape
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('A = ')
print(A)
print('******************************')
print('size of A = ')
print(size_A)

print('******************************')
print('X = ')
print(X)
print('******************************')
print('size of X = ')
print(size_X)

print('******************************')
print('Y = A X')
print(Y)
print('******************************')
print('size of Y = ')
print(size_Y)

******************************
A = 
[[1. 2.]
 [3. 4.]
 [5. 6.]]
******************************
size of A = 
(3, 2)
******************************
X = 
[[10. 20.]
 [30. 40.]]
******************************
size of X = 
(2, 2)
******************************
Y = A X
[[ 70. 100.]
 [150. 220.]
 [230. 340.]]
******************************
size of Y = 
(3, 2)
