### Question 2: Add the two matrices, and perform the multiplication scalar-matrix in Python

In [12]:
import numpy as np

# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
x           = np.array([[1.,2., 3.],[4., 5., 6.]])
size_x      = x.shape

y           = np.array([[10., 20., 30.],[40., 50., 60.]])
size_y      = y.shape

z           = np.array([2.])
size_z      = z.shape

sum_x_y     = x+y
mul_x_z     = np.multiply(x,z)
div_x_z     = np.divide(x,z)

size_sum_x_y    = sum_x_y.shape
size_mul_x_z    = mul_x_z.shape
size_div_x_z    = div_x_z.shape
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('x = ')
print(x)
print('******************************')
print('size of x = ')
print(size_x)

print('******************************')
print('y = ')
print(y)
print('******************************')
print('size of y = ')
print(size_y)

print('******************************')
print('z = ')
print(z)
print('******************************')
print('size of z = ')
print(size_z)

print('******************************')
print('x + y = ')
print(sum_x_y)
print('******************************')
print('size of x + y = ')
print(size_sum_x_y)

print('******************************')
print('x * z = ')
print(mul_x_z)
print('******************************')
print('size of x * z = ')
print(size_mul_x_z)

print('******************************')
print('x / z = ')
print(div_x_z)
print('******************************')
print('size of x / z = ')
print(size_div_x_z)
print('******************************')

******************************
x = 
[[1. 2. 3.]
 [4. 5. 6.]]
******************************
size of x = 
(2, 3)
******************************
y = 
[[10. 20. 30.]
 [40. 50. 60.]]
******************************
size of y = 
(2, 3)
******************************
z = 
[2.]
******************************
size of z = 
(1,)
******************************
x + y = 
[[11. 22. 33.]
 [44. 55. 66.]]
******************************
size of x + y = 
(2, 3)
******************************
x * z = 
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
******************************
size of x * z = 
(2, 3)
******************************
x / z = 
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
******************************
size of x / z = 
(2, 3)
******************************
