### Question 3: Multiply the matrix and vector in Python 

In [15]:
import numpy as np


# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
A       =   np.array([[1., 2.],
                      [3., 4.],
                      [5., 6.]])
size_A  =  A.shape

x       = np.array([[10.],
                    [20.]])
size_x  = x.shape

y       = np.matmul(A,x)
size_y  = y.shape
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('A = ')
print(A)
print('******************************')
print('size of A = ')
print(size_A)

print('******************************')
print('x = ')
print(x)
print('******************************')
print('size of x = ')
print(size_x)

print('******************************')
print('y = A x')
print(y)
print('******************************')
print('size of y = ')
print(size_y)
print('******************************')

******************************
A = 
[[1. 2.]
 [3. 4.]
 [5. 6.]]
******************************
size of A = 
(3, 2)
******************************
x = 
[[10.]
 [20.]]
******************************
size of x = 
(2, 1)
******************************
y = A x
[[ 50.]
 [110.]
 [170.]]
******************************
size of y = 
(3, 1)
******************************
