### Question 5: Compute the matrix transpose in Python. Determine also the matrix inverse in Python.

In [25]:
import numpy as np

# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
A                   = np.array([[1., 2.],
                                [3., 4.]])
size_A              = A.shape

AT                  = np.transpose(A)
size_AT             = AT.shape

mul_AT_A            = np.matmul(AT,A)
size_mul_AT_A       = mul_AT_A.shape

invA                = np.linalg.inv(A)
size_invA           = A.shape

inv_mul_AT_A        = np.linalg.inv(np.matmul(AT,A))
size_inv_mul_AT_A   = inv_mul_AT_A.shape
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('A = ')
print(A)
print('******************************')
print('size of A = ')
print(size_A)

print('******************************')
print('AT = transpose of A ')
print(AT)
print('******************************')
print('size of AT = ')
print(size_AT)

print('******************************')
print('AT A = multiplication of AT and A')
print(mul_AT_A)
print('******************************')
print('size of multiplication of AT and A = ')
print(size_mul_AT_A)

print('******************************')
print('inverse of A = ')
print(invA)
print('******************************')
print('size of inverse of A = ')
print(size_invA)

print('******************************')
print('inverse of multiplication of A transpose and A = ')
print(inv_mul_AT_A)
print('******************************')
print('size of inverse of multiplication of A transpose and A = ')
print(size_inv_mul_AT_A)
print('******************************')

******************************
A = 
[[1. 2.]
 [3. 4.]]
******************************
size of A = 
(2, 2)
******************************
AT = transpose of A 
[[1. 3.]
 [2. 4.]]
******************************
size of AT = 
(2, 2)
******************************
AT A = multiplication of AT and A
[[10. 14.]
 [14. 20.]]
******************************
size of multiplication of AT and A = 
(2, 2)
******************************
inverse of A = 
[[-2.   1. ]
 [ 1.5 -0.5]]
******************************
size of inverse of A = 
(2, 2)
******************************
inverse of multiplication of A transpose and A = 
[[ 5.  -3.5]
 [-3.5  2.5]]
******************************
size of inverse of multiplication of A transpose and A = 
(2, 2)
******************************
